-- Run with Supabase db query --file. Fixtures are rolled back, including net jobs.
begin;
do $$
declare
 a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); code_a uuid:=gen_random_uuid(); code_b uuid:=gen_random_uuid();
 owner_id uuid; case_id uuid; policy uuid; effect jsonb; report_id uuid; contact uuid; conversation uuid; review uuid; next_review uuid; job private.whatsapp_inbox; ticket uuid:=gen_random_uuid();
begin
 select id into owner_id from auth.users limit 1;
 assert owner_id is not null,'test requires one existing auth account';
 insert into public.stores(id,name,return_code) values(a,'Routing test A',code_a),(b,'Routing test B',code_b);
 insert into public.memberships(store_id,user_id,role) values(a,owner_id,'owner');
 insert into public.whatsapp_connections(store_id,phone_number_id,business_account_id,status) values(a,'test-phone','test-waba','CONNECTED'),(b,'test-phone','test-waba','CONNECTED');
 assert public.whatsapp_route('test-phone','sender',null) is null,'no guessed store';
 assert public.whatsapp_route('test-phone','sender',code_a)=a,'route A';
 assert public.whatsapp_route('test-phone','sender',null)=a,'remember A';
 assert public.whatsapp_route('test-phone','other-sender',null) is null,'sender isolation';
 assert public.whatsapp_route('test-phone','sender',code_b)=b,'explicit switch B';
 update public.whatsapp_connections set status='DISCONNECTED' where store_id=b;
 assert public.whatsapp_route('test-phone','sender',null) is null,'disconnected store not routed';
 assert public.whatsapp_route('test-phone','sender',code_a)=a,'switch back A';
 assert public.whatsapp_route('test-phone','sender',gen_random_uuid()) is null,'invalid code';
 assert public.whatsapp_route('test-phone','sender',null) is null,'invalid link clears route';
 insert into public.whatsapp_contacts(store_id,wa_id) values(a,'966500000000') returning id into contact;
 insert into public.whatsapp_conversations(store_id,contact_id) values(a,contact) returning id into conversation;
 review:=public.request_identity_review(conversation,'SA-10492');
 assert public.request_identity_review(conversation,'SA-10492')=review,'pending request is idempotent';
 begin
  perform public.resolve_identity_review(review,gen_random_uuid(),jsonb_build_object('storeId',a),'Checked');
  raise exception 'unauthorized approval accepted';
 exception when others then assert sqlerrm='not_authorized','unauthorized actor rejected'; end;
 begin
  perform public.resolve_identity_review(review,owner_id,jsonb_build_object('storeId',b),'Checked');
  raise exception 'cross-store approval accepted';
 exception when others then assert sqlerrm='store_mismatch','cross-store facts rejected'; end;
 assert public.resolve_identity_review(review,owner_id,null,'Unable to verify'),'decline';
 next_review:=public.request_identity_review(conversation,'SA-10492');
 assert next_review<>review,'declined requests can be retried';
 assert public.resolve_identity_review(next_review,owner_id,jsonb_build_object('storeId',a,'orderId','SA-10492'),'Confirmed via existing support thread'),'approve';
 assert public.get_identity_review_facts(next_review,conversation)->>'orderId'='SA-10492','approved facts';
 assert public.get_identity_review_facts(next_review,gen_random_uuid()) is null,'conversation binding';
 assert not public.resolve_identity_review(next_review,owner_id,null,'Again'),'decision immutable';
 update private.identity_review_facts set expires_at=now()-interval '1 second' where review_id=next_review;
 assert public.get_identity_review_facts(next_review,conversation) is null,'expired grant hidden';
 assert public.request_identity_review(conversation,'SA-10492')<>next_review,'expired grant can be reviewed again';
 assert not has_table_privilege('authenticated','private.identity_review_facts','SELECT'),'private facts inaccessible';
 assert not has_function_privilege('authenticated','public.get_identity_review_facts(uuid,uuid)','EXECUTE'),'private RPC inaccessible';
 assert not has_function_privilege('authenticated','public.resolve_identity_review(uuid,uuid,jsonb,text)','EXECUTE'),'approval actor cannot be forged through RPC';

 perform public.enqueue_whatsapp_message('test-phone','queue-sender','{"id":"fixture-msg-1","from":"queue-sender","type":"text","text":{"body":"hello"}}',null);
 perform public.enqueue_whatsapp_message('test-phone','queue-sender','{"id":"fixture-msg-1","from":"queue-sender"}',null);
 perform public.enqueue_whatsapp_message('test-phone','queue-sender','{"id":"fixture-msg-2","from":"queue-sender"}',null);
 assert (select count(*) from private.whatsapp_inbox where id='fixture-msg-1')=1,'inbox duplicate protection';
 select * into job from public.claim_whatsapp_inbox();
 assert job.id='fixture-msg-1','FIFO first';
 assert not exists(select 1 from public.claim_whatsapp_inbox()),'same sender serialized';
 perform public.finish_whatsapp_inbox('fixture-msg-1','temporary outage',false);
 assert not exists(select 1 from public.claim_whatsapp_inbox()),'later message waits for retry';
 update private.whatsapp_inbox set available_at=now() where id='fixture-msg-1';
 select * into job from public.claim_whatsapp_inbox();
 assert job.id='fixture-msg-1','retry same first message';
 perform public.save_whatsapp_reply('fixture-msg-1','{"plan":{"kind":"text","body":"hello"}}');
 perform public.mark_whatsapp_send_started('fixture-msg-1');
 update private.whatsapp_inbox set lease_until=now()-interval '1 second' where id='fixture-msg-1';
 select * into job from public.claim_whatsapp_inbox();
 assert job.id='fixture-msg-2','uncertain send does not block customer forever';
 perform public.commit_whatsapp_transition('fixture-msg-2',conversation,'AWAITING_REASON','{}','{"plan":{"kind":"text","body":"Choose reason"}}');
 assert (select step from public.get_whatsapp_flow_state(conversation))='AWAITING_REASON','flow transition committed';
 assert (select reply->'plan'->>'body' from private.whatsapp_inbox where id='fixture-msg-2')='Choose reason','reply committed with transition';
 report_id:=public.record_whatsapp_report('fixture-msg-2',jsonb_build_object('store_id',a,'conversation_id',conversation,'report_type','BUG','message','Test report','context','{}'::jsonb));
 assert public.record_whatsapp_report('fixture-msg-2','{}')=report_id,'report replay idempotent';
 insert into public.policy_versions(store_id,version_label,source_text,rules_snapshot,published_by) values(a,'test-v1','Test policy','[]',owner_id) returning id into policy;
 effect:=public.record_whatsapp_decision('fixture-msg-2',jsonb_build_object('p_store_id',a,'p_policy_version_id',policy,'p_order_id','SA-10492','p_outcome','ELIGIBLE','p_reason_codes','["ALL_RULES_PASSED"]'::jsonb,'p_order_facts','{}'::jsonb,'p_policy_snapshot','{}'::jsonb,'p_customer_snapshot','{}'::jsonb,'p_item_snapshot','{}'::jsonb),'{}');
 assert public.record_whatsapp_decision('fixture-msg-2','{}','{}')=effect,'decision replay idempotent';
 case_id:=public.create_return_case_from_decision((effect->>'decisionId')::uuid,'{}','{}');
 assert public.create_return_case_from_decision((effect->>'decisionId')::uuid,'{}','{}')=case_id,'case replay idempotent';
 perform public.commit_whatsapp_transition('fixture-msg-2',conversation,'COMPLETE',jsonb_build_object('caseId',case_id),'{"plan":{"kind":"text","body":"Submitted"}}');
 assert (select id from public.get_whatsapp_cases(conversation))=case_id,'track linked case';
 assert not exists(select 1 from public.get_whatsapp_cases(gen_random_uuid())),'case history conversation isolation';
 assert public.get_whatsapp_case_conversation(case_id)=conversation,'older case notification routing';
 update private.whatsapp_inbox set lease_until=now()-interval '1 second' where id='fixture-msg-2';
 select * into job from public.claim_whatsapp_inbox();
 assert job.id='fixture-msg-2' and job.reply is not null,'prepared but unsent reply recovers';
 assert (select status from private.whatsapp_inbox where id='fixture-msg-1')='UNCERTAIN','do not resend ambiguous send';
 insert into private.whatsapp_worker_tickets values(ticket,now()+interval '1 minute');
 assert public.consume_whatsapp_worker_ticket(ticket),'worker ticket accepted';
 assert not public.consume_whatsapp_worker_ticket(ticket),'worker ticket single-use';
 assert not has_table_privilege('authenticated','private.whatsapp_inbox','SELECT'),'raw inbox is private';
 assert not has_function_privilege('anon','public.consume_whatsapp_worker_ticket(uuid)','EXECUTE'),'no client worker access';
end $$;
rollback;
